[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "sh /app/bin/docker-entrypoint.sh"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 100
